name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: henrydocker992
          password: sR!k2.e2g78s2!7

      - name: Build Docker image
        run: |
          docker build -t HenryDev0888/DevPortfolio:latest .

      - name: Push Docker image
        run: |
          docker push HenryDev0888/DevPortfolio:latest
